# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/qoomon/git-conventional-commits
  rev: v2.7.2
  hooks:
  - id: conventional-commits