name: 'Check Docker Image building'

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & Run Docker image
        run: |
          cd docker
          # docker compose build
          docker build -t my-test-image .
          docker run --rm my-test-image
